#define ST_LED_R       2
#define ST_LED_B       3
#define ST_LED_G       4
#define LE_IL          5
#define Z80_RESET      6
#define nMEM_LATCH_OE  7
#define TMS            8
#define TDI            9
#define TDO           10
#define TCK           11
#define VREF          12
#define RST_CTRL_REG  13
#define CTRL_CLK      14
#define RST_DATA_REG  15
#define nOE_OL        16
#define A16b          17 
#define GET_CTRL_REG  18
#define GET_DATA_REG  19
#define A17b          20 
#define A18b          21 
#define D0            22
#define D1            23
#define D2            24
#define D3            25
#define D4            26
#define D5            27
#define D6            28
#define D7            29
#define A15b          30
#define A14b          31
#define A13b          32
#define A12b          33
#define A11b          34
#define A10b          35
#define A9b           36
#define A8b           37
#define nMEM_CE       38
#define ALE           39
#define nMEM_OE       40
#define nWRb          41
#define nWAIT         42
#define FULLPAGING    43
#define EN_M1_NOT     44
#define SPEAKER       45
#define SPARE1        46
#define SD_LED        47
#define ROM_WR_EN     48
#define SEL_128CHARS  49
#define MISO          50
#define MOSI          51
#define SCLK          52
#define SS_SD         53   

#define OUTPUT_LATCH  PORTK         
#define INPUT_LATCH   PINF
